// @flow

export const ACTION = {
  FETCH_PHOTOS_REQUESTED: 'FETCH_PHOTOS_REQUESTED',
  FETCH_PHOTOS_LOADING: 'FETCH_PHOTOS_LOADING',
  FETCH_PHOTOS_SUCCESS: 'FETCH_PHOTOS_SUCCESS',
  FETCH_PHOTOS_FAIL: 'FETCH_PHOTOS_FAIL',
};
