// @flow

export const ACTION = {
  CHANGE_PHOTOS_FILTER: 'CHANGE_PHOTOS_FILTER',
  FETCH_PHOTOS_REQUESTED: 'FETCH_PHOTOS_REQUESTED',
  FETCH_PHOTOS_LOADING: 'FETCH_PHOTOS_LOADING',
  FETCH_PHOTOS_SUCCESS: 'FETCH_PHOTOS_SUCCESS',
  FETCH_PHOTOS_FAIL: 'FETCH_PHOTOS_FAIL',
  TO_SINGLE_PHOTO: 'TO_SINGLE_PHOTO',
};

export const PHOTOS_FILTERS = {
  LATEST: 'latest',
  POPULAR: 'popular',
  OLDEST: 'oldest',
};
