# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'unsplashapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for unsplashapp

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Fabric', '~> 1.7.5'
  pod 'Crashlytics', '~> 3.10.4'

end
